"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sean R. Spillane"
email = "sean@spillane.us"

[ui]
pager = "less -FRX"
default-command = ['util', 'exec', '--', 'bash', '-c', """
jj status
echo Log:
jj log -n 10 -r 'ancestors(@,5)::descendants(@,5)'
""", ""]

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
'''

[aliases]
pullup = [
  "util", "exec", "--",
  "bash", "-c", """
    set -euo pipefail
    if [ $# -ge 1 ]; then
      branch=$1
    else
      # List the bookmarks on the working-copy commit and take the first
      names=$(jj log --template 'bookmarks ++ "\n"' --no-graph | grep . | head -1)
      branch=${names%%,*}
    fi
    # Move that bookmark back one commit
    echo jj bookmark move --from "$branch" --to @-
    jj bookmark move --from "$branch" --to @-
  """,
  "_"  # placeholder for $0
]
aliases = ["util", "exec", "--", "bash", "-c", """
#!/bin/bash 
set -euo pipefail
jj config list aliases | pygmentize -l toml -f 16m -O style=dracula
""", ""]

up = ["util", "exec", "--", "bash", "-c", """
#!/bin/bash
set -euo pipefail
if [ $# -gt 1 ]; then
  cat >&2 <<-'EOF'
  Usage: jj up [n=1]

  Go forward 1 or more commits.
EOF
  exit 1
fi
n=${1:-1}
rev=$(
  jj log \
    -r "descendants(@,$((n+1))) ~ descendants(@,$n)" \
    --template 'self.change_id()' \
    --no-graph
)

jj edit "$rev"
""", ""]

down = ["util", "exec", "--", "bash", "-c", """
#!/bin/bash
set -euo pipefail
if [ $# -gt 1 ]; then
  cat >&2 <<-'EOF'
  Usage: jj down [n=1]

  Go back 1 or more commits.
EOF
  exit 1
fi
n=${1:-1}
rev=$(
  jj log \
    -r "ancestors(@,$((n+1))) ~ ancestors(@,$n)" \
    --template 'self.change_id()' \
    --no-graph
)

jj edit "$rev"
""", ""]
